type communityLinks {
  url: String!
  name: String!
  description: String!
  archived: Boolean
}

type royalStreams {
  url: String!
  name: String!
}

type Query {
  allCommunityLinks: [communityLinks!]!
  allRoyalStreams: [royalStreams!]!
}
