type communityLinks {
  url: String!
  name: String!
  description: String!
  archived: Boolean
}

type royalStreams {
  url: String!
  name: String!
}

type announcements {
  dateCreated: String!
  dateModified: String
  dateArchived: String
  createdBy: String!
  modifiedBy: String
  archived: Boolean
  title: String!
  imageURL: String
  videoURL: String
  embed: String
  body: String!
  type: String!
  sections: String
}

type Query {
  allCommunityLinks: [communityLinks!]!
  allRoyalStreams: [royalStreams!]!
  allAnnouncements: [announcements!]!
}
