[build]
    functions = "functions"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
    force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://www.royal-clan.com/BattleRoyale"
  to = "https://www.royal-clan.com/BattleRoyale!"
  status = 200